name: "API — Karate + Maven"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      java-version:
        description: "Java version"
        required: false
        default: "17"
        type: choice
        options: ["11", "17", "21"]
      environment:
        description: "Target environment"
        required: false
        default: "staging"
        type: choice
        options: ["dev", "staging", "production"]
      tags:
        description: "Karate tags to run (e.g. ~@ignore)"
        required: false
        default: "~@ignore"

env:
  JAVA_VERSION: ${{ inputs.java-version || '17' }}
  ENVIRONMENT: ${{ inputs.environment || 'staging' }}
  KARATE_TAGS: ${{ inputs.tags || '~@ignore' }}

jobs:
  setup:
    name: "Setup — Java ${{ inputs.java-version || '17' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-karate-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-karate-${{ runner.os }}-

      - name: Validate project
        run: mvn validate --no-transfer-progress

  test:
    name: "Tests — ${{ matrix.environment }}"
    runs-on: ubuntu-latest
    needs: setup
    fail-fast: false
    strategy:
      matrix:
        environment: ["${{ env.ENVIRONMENT }}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven"

      - name: Restore Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-karate-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Run Karate tests
        run: |
          mvn test \
            -Dkarate.env=${{ matrix.environment }} \
            -Dkarate.options="--tags ${{ env.KARATE_TAGS }}" \
            --no-transfer-progress
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Upload Karate HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report-${{ matrix.environment }}
          path: target/karate-reports/
          retention-days: 14

      - name: Upload Surefire results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-karate-${{ matrix.environment }}
          path: target/surefire-reports/
          retention-days: 7

  report:
    name: "Report — Summary"
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Generate summary
        run: |
          echo "## 🥋 Karate API Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Java version | ${{ env.JAVA_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Environment | ${{ env.ENVIRONMENT }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Tags | ${{ env.KARATE_TAGS }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Status | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
