name: "API — REST-Assured + Java"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      java-version:
        description: "Java version"
        required: false
        default: "17"
        type: choice
        options: ["11", "17", "21"]
      environment:
        description: "Target environment"
        required: false
        default: "staging"
        type: choice
        options: ["dev", "staging", "production"]
      test-groups:
        description: "TestNG groups to run"
        required: false
        default: "smoke,regression"

env:
  JAVA_VERSION: ${{ inputs.java-version || '17' }}
  ENVIRONMENT: ${{ inputs.environment || 'staging' }}
  TEST_GROUPS: ${{ inputs.test-groups || 'smoke,regression' }}

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-restassured-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - run: mvn dependency:resolve --no-transfer-progress

  test:
    name: "Tests — ${{ env.ENVIRONMENT }}"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Restore Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-restassured-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Run REST-Assured tests
        run: |
          mvn test \
            -Denv=${{ env.ENVIRONMENT }} \
            -Dgroups="${{ env.TEST_GROUPS }}" \
            --no-transfer-progress
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restassured-surefire-${{ env.ENVIRONMENT }}
          path: target/surefire-reports/
          retention-days: 7

      - name: Upload ExtentReports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restassured-extent-${{ env.ENVIRONMENT }}
          path: target/extent-reports/
          retention-days: 14

  report:
    name: "Report"
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - run: |
          echo "## 🔗 REST-Assured Results" >> $GITHUB_STEP_SUMMARY
          echo "| Java | Env | Groups | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|-----|--------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| ${{ env.JAVA_VERSION }} | ${{ env.ENVIRONMENT }} | ${{ env.TEST_GROUPS }} | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
